import { relations, sql } from "drizzle-orm"
import {
  boolean,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core"

import { user } from "./auth-schema"

/**
 * Better Auth tables live in `auth-schema.ts`, generated by the official
 * Better Auth CLI (`npx auth generate`). They are re-exported here so the
 * Drizzle client, drizzle-kit and the auth adapter all see one schema.
 * Do not hand-edit the generated file; regenerate it instead.
 */
export * from "./auth-schema"

/**
 * Profile-level data for a single imported LinkedIn creator.
 *
 * `ownerKey` is the tenancy boundary: it holds the Better Auth user id for
 * authenticated imports, or the shared demo key for the unauthenticated demo.
 * `userId` carries the real foreign key when a session exists.
 */
export const creatorProfiles = pgTable("creator_profiles", {
  id: uuid("id").primaryKey().defaultRandom(),
  ownerKey: text("owner_key").notNull().unique(),
  // Set once a profile is imported by an authenticated user. Nullable so the
  // pre-auth demo row survives the migration untouched.
  userId: text("user_id").references(() => user.id, { onDelete: "cascade" }),
  linkedinUrl: text("linkedin_url").notNull(),
  name: text("name"),
  headline: text("headline"),
  location: text("location"),
  avatarUrl: text("avatar_url"),
  followers: integer("followers"),
  // JSONB is used only for the flexible, shape-unstable profile arrays.
  experience: jsonb("experience")
    .$type<unknown[]>()
    .notNull()
    .default(sql`'[]'::jsonb`),
  education: jsonb("education")
    .$type<unknown[]>()
    .notNull()
    .default(sql`'[]'::jsonb`),
  skills: jsonb("skills")
    .$type<string[]>()
    .notNull()
    .default(sql`'[]'::jsonb`),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
})

/**
 * Public posts belonging to a creator profile. Searchable scalar fields stay
 * as real columns so they can be filtered and aggregated in SQL.
 */
export const linkedinPosts = pgTable(
  "linkedin_posts",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    profileId: uuid("profile_id")
      .notNull()
      .references(() => creatorProfiles.id, { onDelete: "cascade" }),
    externalId: text("external_id").notNull(),
    url: text("url"),
    text: text("text"),
    publishedAt: timestamp("published_at", { withTimezone: true }),
    reactions: integer("reactions"),
    comments: integer("comments"),
    shares: integer("shares"),
    isRepost: boolean("is_repost").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (table) => [
    // Upsert target: re-importing the same post updates it instead of
    // inserting a duplicate.
    unique("linkedin_posts_profile_id_external_id_unique").on(
      table.profileId,
      table.externalId
    ),
  ]
)

export const creatorProfilesRelations = relations(
  creatorProfiles,
  ({ many, one }) => ({
    posts: many(linkedinPosts),
    owner: one(user, {
      fields: [creatorProfiles.userId],
      references: [user.id],
    }),
  })
)

export const linkedinPostsRelations = relations(linkedinPosts, ({ one }) => ({
  profile: one(creatorProfiles, {
    fields: [linkedinPosts.profileId],
    references: [creatorProfiles.id],
  }),
}))

export type CreatorProfileRow = typeof creatorProfiles.$inferSelect
export type NewCreatorProfileRow = typeof creatorProfiles.$inferInsert
export type LinkedInPostRow = typeof linkedinPosts.$inferSelect
export type NewLinkedInPostRow = typeof linkedinPosts.$inferInsert
